// Package consolecontract generates TypeScript directly from the Go API types.
package consolecontract

import (
	"bytes"
	"encoding/json"
	"fmt"
	"path"
	"reflect"
	"sort"
	"strings"
	"time"

	"github.com/ding-labs/ding/internal/control"
	"github.com/ding-labs/ding/internal/plan"
	"github.com/ding-labs/ding/internal/replay"
	"github.com/ding-labs/ding/internal/store"
	"github.com/ding-labs/ding/internal/watch"
	"github.com/ding-labs/ding/internal/watchrun"
)

func Generate() []byte {
	definitions := map[string]string{}
	var typeOf func(reflect.Type) string
	typeOf = func(t reflect.Type) string {
		if t == reflect.TypeFor[time.Time]() {
			return "string"
		}
		if t == reflect.TypeFor[json.RawMessage]() {
			return "unknown"
		}
		switch t.Kind() {
		case reflect.Pointer:
			return typeOf(t.Elem()) + " | null"
		case reflect.Bool:
			return "boolean"
		case reflect.String:
			return "string"
		case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64, reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Float32, reflect.Float64:
			return "number"
		case reflect.Slice, reflect.Array:
			if t.Elem().Kind() == reflect.Uint8 {
				return "string"
			}
			return "Array<" + typeOf(t.Elem()) + ">"
		case reflect.Map:
			return "Record<string, " + typeOf(t.Elem()) + ">"
		case reflect.Interface:
			return "unknown"
		case reflect.Struct:
			pkg := path.Base(t.PkgPath())
			name := strings.ToUpper(pkg[:1]) + pkg[1:] + t.Name()
			if _, ok := definitions[name]; ok {
				return name
			}
			definitions[name] = ""
			var out strings.Builder
			fmt.Fprintf(&out, "export interface %s {\n", name)
			for i := 0; i < t.NumField(); i++ {
				f := t.Field(i)
				if !f.IsExported() {
					continue
				}
				parts := strings.Split(f.Tag.Get("json"), ",")
				field := parts[0]
				if field == "-" {
					continue
				}
				if field == "" {
					field = f.Name
				}
				optional := ""
				if strings.Contains(f.Tag.Get("json"), "omitempty") {
					optional = "?"
				}
				fmt.Fprintf(&out, "  %s%s: %s;\n", field, optional, typeOf(f.Type))
			}
			out.WriteString("}\n")
			definitions[name] = out.String()
			return name
		default:
			panic("unsupported API type " + t.String())
		}
	}
	for _, v := range []any{store.WatchPage{}, store.EventSummaryPage{}, store.DeliveryPage{}, store.DestinationPage{}, watchrun.Status{}, control.CompileResult{}, control.Verification{}, control.Info{}, control.BrowserSession{}, plan.Bundle{}, watch.Definition{}, watch.Event{}, watch.Observation{}, store.WatchSummary{}, store.DeliveryInspection{}, store.EventPage{}, store.ObservationPage{}, watchrun.Doctor{}, watchrun.ApplyRequest{}, watchrun.ApplyResult{}, replay.Evidence{}, replay.Report{}} {
		typeOf(reflect.TypeOf(v))
	}
	names := make([]string, 0, len(definitions))
	for k := range definitions {
		names = append(names, k)
	}
	sort.Strings(names)
	var out bytes.Buffer
	out.WriteString("// Generated by go run ./cmd/console-contract. Do not edit.\n\n")
	for _, name := range names {
		out.WriteString(definitions[name])
		out.WriteByte('\n')
	}
	return out.Bytes()
}
