package control

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/hex"
	"fmt"
	"net"
	"net/http"
	"net/url"
	"runtime"
	"strings"
	"sync"
	"time"

	"github.com/ding-labs/ding/internal/store"
	"github.com/ding-labs/ding/internal/watch"
	"github.com/ding-labs/ding/internal/watchrun"
)

type ConsoleConfig struct {
	Version  string
	Origin   string
	Listen   string
	StateDir string
	Assets   http.Handler
	// Reference is generated by Cobra, not interpreted as a shell command.
	Reference func(string) (string, error)
	now       func() time.Time
}
type Info struct {
	Version    string          `json:"version"`
	APIVersion string          `json:"apiVersion"`
	Schema     int             `json:"schema"`
	OS         string          `json:"os"`
	Arch       string          `json:"arch"`
	Console    bool            `json:"console"`
	Origin     string          `json:"origin"`
	Listen     string          `json:"listen"`
	StateDir   string          `json:"stateDir"`
	Limits     watchrun.Limits `json:"limits"`
	Time       time.Time       `json:"time"`
}
type BrowserSession struct {
	CSRF      string    `json:"csrf"`
	ExpiresAt time.Time `json:"expiresAt"`
}
type BrowserHandoff struct {
	Token     string    `json:"token"`
	URL       string    `json:"url"`
	ExpiresAt time.Time `json:"expiresAt"`
}
type browserSession struct{ BrowserSession }
type browserOwnerKey struct{}
type browserAccess struct {
	mu           sync.Mutex
	origin, host string
	cookieName   string
	secure       bool
	handoffs     map[string]time.Time
	sessions     map[string]browserSession
	now          func() time.Time
}

func randomToken() string {
	var b [32]byte
	if _, err := rand.Read(b[:]); err != nil {
		panic(err)
	}
	return hex.EncodeToString(b[:])
}
func ValidUIOrigin(raw string) bool {
	u, err := url.Parse(raw)
	if err != nil || u.User != nil || u.RawQuery != "" || u.Fragment != "" || u.Path != "" || u.Host == "" {
		return false
	}
	if u.Scheme == "https" {
		return true
	}
	ip := net.ParseIP(u.Hostname())
	return u.Scheme == "http" && (u.Hostname() == "localhost" || (ip != nil && ip.IsLoopback()))
}

// ConsoleHandler adds browser authentication without changing bearer API access.
func ConsoleHandler(app *watchrun.App, c Credentials, cfg ConsoleConfig) http.Handler {
	u, _ := url.Parse(cfg.Origin)
	b := &browserAccess{cookieName: fmt.Sprintf("ding_console_%x", sha256.Sum256([]byte(cfg.Origin)))[:29], origin: cfg.Origin, handoffs: map[string]time.Time{}, sessions: map[string]browserSession{}, now: time.Now}
	if cfg.now != nil {
		b.now = cfg.now
	}
	if u != nil {
		b.host = u.Host
		b.secure = u.Scheme == "https"
	}
	enabled := cfg.Assets != nil && ValidUIOrigin(cfg.Origin)
	api := http.NewServeMux()
	api.Handle("/", Handler(app, c))
	api.HandleFunc("GET /v1/info", func(w http.ResponseWriter, r *http.Request) {
		write(w, 200, Info{cfg.Version, watch.APIVersion, store.SchemaVersion, runtime.GOOS, runtime.GOARCH, enabled, cfg.Origin, cfg.Listen, cfg.StateDir, app.Limits, time.Now().UTC()}, nil)
	})
	api.HandleFunc("POST /v1/browser/handoff", func(w http.ResponseWriter, r *http.Request) {
		if !enabled {
			fail(w, 409, "console_unavailable", "use a console-enabled Ding build and a configured UI origin")
			return
		}
		// Only a caller holding the admin bearer credential may mint launch links.
		if !bearer(r, c.Admin) {
			fail(w, 403, "bearer_required", "launch Ding Console with ding ui")
			return
		}
		b.mu.Lock()
		defer b.mu.Unlock()
		b.prune()
		if len(b.handoffs) >= 32 {
			fail(w, 429, "handoff_limit", "too many outstanding console launch links")
			return
		}
		token := randomToken()
		expiry := b.now().Add(time.Minute)
		b.handoffs[token] = expiry
		write(w, 200, BrowserHandoff{token, cfg.Origin + "/ui/#handoff=" + token, expiry}, nil)
	})
	// New console routes are protected by the same outer authorization boundary.
	consoleRoutes(api, app, cfg)
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Cache-Control", "no-store")
		w.Header().Set("X-Content-Type-Options", "nosniff")
		if r.URL.Path == "/health" {
			api.ServeHTTP(w, r)
			return
		}
		if r.URL.Path == "/ui" || strings.HasPrefix(r.URL.Path, "/ui/") {
			if !enabled {
				http.Error(w, "Console unavailable. Build Ding with console assets; see docs/console.md.", 404)
				return
			}
			if r.Host != b.host {
				http.Error(w, "unrecognized console host", 403)
				return
			}
			if r.URL.Path == "/ui" {
				http.Redirect(w, r, "/ui/", http.StatusTemporaryRedirect)
				return
			}
			cfg.Assets.ServeHTTP(w, r)
			return
		}
		if strings.HasPrefix(r.URL.Path, "/v1/ingest/") {
			api.ServeHTTP(w, r)
			return
		}
		if r.URL.Path == "/v1/browser/session" && r.Method == "POST" {
			if !enabled || r.Host != b.host || r.Header.Get("Origin") != b.origin {
				fail(w, 403, "invalid_origin", "open the launch link from ding ui on the configured origin")
				return
			}
			var request struct {
				Token string `json:"token"`
			}
			if decode(w, r, &request) != nil {
				fail(w, 400, "invalid_request", "a handoff token is required")
				return
			}
			b.mu.Lock()
			defer b.mu.Unlock()
			b.prune()
			expiry, ok := b.handoffs[request.Token]
			if !ok || !expiry.After(b.now()) {
				fail(w, 401, "handoff_expired", "this link expired or was used; run ding ui again")
				return
			}
			if len(b.sessions) >= 128 {
				fail(w, 429, "session_limit", "too many console sessions")
				return
			}
			delete(b.handoffs, request.Token)
			token := randomToken()
			s := browserSession{BrowserSession{randomToken(), b.now().Add(8 * time.Hour)}}
			b.sessions[token] = s
			http.SetCookie(w, &http.Cookie{Name: b.cookieName, Value: token, Path: "/v1", HttpOnly: true, Secure: b.secure, SameSite: http.SameSiteStrictMode, Expires: s.ExpiresAt})
			write(w, 200, s.BrowserSession, nil)
			return
		}
		if bearer(r, c.Admin) {
			api.ServeHTTP(w, r)
			return
		}
		if !enabled || r.Host != b.host {
			fail(w, 401, "unauthorized", "launch Ding Console with ding ui")
			return
		}
		cookie, err := r.Cookie(b.cookieName)
		if err != nil {
			fail(w, 401, "unauthorized", "launch Ding Console with ding ui")
			return
		}
		b.mu.Lock()
		b.prune()
		s, ok := b.sessions[cookie.Value]
		b.mu.Unlock()
		if !ok {
			fail(w, 401, "session_expired", "session expired; run ding ui again")
			return
		}
		if origin := r.Header.Get("Origin"); origin != "" && origin != b.origin {
			fail(w, 403, "invalid_origin", "request origin does not match this console")
			return
		}
		if r.Method != "GET" && r.Method != "HEAD" && (r.Header.Get("Origin") != b.origin || subtle.ConstantTimeCompare([]byte(r.Header.Get("X-Ding-CSRF")), []byte(s.CSRF)) != 1) {
			fail(w, 403, "invalid_csrf", "refresh the console session before changing state")
			return
		}
		if r.URL.Path == "/v1/browser/session" {
			switch r.Method {
			case "GET":
				write(w, 200, s.BrowserSession, nil)
			case "DELETE":
				b.mu.Lock()
				delete(b.sessions, cookie.Value)
				b.mu.Unlock()
				http.SetCookie(w, &http.Cookie{Name: b.cookieName, Value: "", Path: "/v1", HttpOnly: true, Secure: b.secure, SameSite: http.SameSiteStrictMode, MaxAge: -1})
				write(w, 200, map[string]bool{"loggedOut": true}, nil)
			default:
				fail(w, 405, "method_not_allowed", "use GET, POST or DELETE")
			}
			return
		}
		if r.URL.Path == "/v1/browser/handoff" {
			fail(w, 403, "bearer_required", "launch Ding Console with ding ui")
			return
		}
		forwarded := r.Clone(context.WithValue(r.Context(), browserOwnerKey{}, cookie.Value))
		forwarded.Header = r.Header.Clone()
		forwarded.Header.Set("Authorization", "Bearer "+c.Admin)
		api.ServeHTTP(w, forwarded)
	})
}
func bearer(r *http.Request, want string) bool {
	v := strings.TrimPrefix(r.Header.Get("Authorization"), "Bearer ")
	return v != r.Header.Get("Authorization") && subtle.ConstantTimeCompare([]byte(v), []byte(want)) == 1
}
func (b *browserAccess) prune() {
	now := b.now()
	for k, v := range b.handoffs {
		if !v.After(now) {
			delete(b.handoffs, k)
		}
	}
	for k, v := range b.sessions {
		if !v.ExpiresAt.After(now) {
			delete(b.sessions, k)
		}
	}
}
