package main

import (
	"log"
	"os"

	"github.com/spf13/cobra/doc"

	"github.com/ding-labs/ding/internal/watchcli"
)

func main() {
	outDir := "docs/cli"
	if len(os.Args) > 1 {
		outDir = os.Args[1]
	}
	if err := os.MkdirAll(outDir, 0755); err != nil {
		log.Fatal(err)
	}
	root := watchcli.Root("dev")
	// Suppress the "Auto generated by spf13/cobra on <date>" footer.
	// Without this, every CI run produces a timestamp diff even when nothing changed.
	root.DisableAutoGenTag = true
	if err := doc.GenMarkdownTree(root, outDir); err != nil {
		log.Fatal(err)
	}
}
