// Generated by go run ./cmd/console-contract. Do not edit.

export interface ConditionSample {
  at: string;
  value: number;
  sequence: number;
}

export interface ConditionState {
  baselineSequence?: number;
  incidentEvent?: string;
  healthEvent?: string;
  freshSequence?: number;
  missingAt?: string;
  entity: string;
  open: boolean;
  matches: number;
  recoveries: number;
  lastAt: string;
  lastFired: string;
  lastSequence: number;
  sourceUnhealthy: boolean;
  samples?: Array<ConditionSample>;
  overflowUntil?: string;
  clockWindowUntil?: string;
  evidence?: Array<number>;
  baseline?: unknown;
  seen?: Record<string, string>;
}

export interface ControlBrowserSession {
  csrf: string;
  expiresAt: string;
}

export interface ControlInfo {
  version: string;
  apiVersion: string;
  schema: number;
  os: string;
  arch: string;
  console: boolean;
  origin: string;
  listen: string;
  stateDir: string;
  limits: WatchrunLimits;
  time: string;
}

export interface PlanBundle {
  watches: Array<PlanCompiled>;
  destinations: Array<PlanCompiledDestination>;
}

export interface PlanCompiled {
  definition: WatchDefinition;
  revision: string;
  fingerprint: string;
  permissions: Array<string>;
}

export interface PlanCompiledDestination {
  definition: WatchDestination;
  revision: string;
}

export interface ReplayCheckpoint {
  prior: ConditionState;
  input: WatchObservation;
  sourceRecovered?: boolean;
}

export interface ReplayEvidence {
  definition: WatchDefinition;
  event: WatchEvent;
  checkpoint?: ReplayCheckpoint | null;
  replayStatus: string;
}

export interface ReplayReport {
  watchId: string;
  revision: string;
  observations: number;
  events: Array<WatchEvent>;
  states: Record<string, ConditionState>;
}

export interface StoreAttempt {
  attempt: number;
  at: string;
  outcome: string;
  detail: string;
}

export interface StoreDeliveryInspection {
  intent: StoreIntent;
  attempts: Array<StoreAttempt>;
  before: number;
}

export interface StoreDeliverySummary {
  id: number;
  eventId: string;
  destinationId: string;
  destinationRevision: string;
  status: string;
  attempts: number;
  nextAt: string;
  lastError?: string;
}

export interface StoreEntitySummary {
  key: string;
  open: boolean;
  sourceUnhealthy: boolean;
  matches: number;
  recoveries: number;
  lastSequence: number;
  samples: number;
}

export interface StoreEventPage {
  events: Array<WatchEvent>;
  cursor: string;
  more: boolean;
}

export interface StoreHealth {
  sqlite: string;
  schema: number;
  journal: string;
  synchronous: number;
  integrity: string;
  databaseBytes: number;
  walBytes: number;
}

export interface StoreIntent {
  id: number;
  eventId: string;
  watchId: string;
  destinationId: string;
  destinationRevision: string;
  payload: string;
  status: string;
  attempts: number;
  nextAt: string;
  cycleStartedAt: string;
  createdAt: string;
}

export interface StoreObservationPage {
  observations: Array<WatchObservation>;
  after: number;
  more: boolean;
}

export interface StoreUsage {
  watches: number;
  pending: number;
  liveBytes: number;
  observations: number;
  events: number;
  entities: number;
  timers: number;
}

export interface StoreWatchRecord {
  plan: PlanCompiled;
  generation: number;
  status: string;
  nextAt: string;
  cursor?: string;
  lastInputAt?: string;
  lastError?: string;
}

export interface StoreWatchSummary {
  watch: StoreWatchRecord;
  entities: Array<StoreEntitySummary>;
  entitiesAfter: string;
  entitiesMore: boolean;
  deliveries: Array<StoreDeliverySummary>;
  deliveriesBefore: number;
  deliveriesMore: boolean;
}

export interface WatchCondition {
  field?: string;
  operator?: string;
  value: unknown;
  numeric?: string;
  missingFor?: string;
  dedupFor?: string;
}

export interface WatchDefinition {
  apiVersion: string;
  kind: string;
  metadata: WatchMetadata;
  spec: WatchSpec;
}

export interface WatchDestination {
  apiVersion: string;
  kind: string;
  metadata: WatchMetadata;
  spec: WatchDestinationSpec;
}

export interface WatchDestinationSpec {
  type: string;
  urlRef?: WatchSecretRef | null;
  headers?: Record<string, WatchSecretRef>;
  maxAttempts: number;
  maxAge: string;
  initialBackoff: string;
}

export interface WatchEvent {
  id: string;
  sequence: number;
  watchId: string;
  revision: string;
  entity: string;
  type: string;
  at: string;
  message: string;
  fields?: Record<string, unknown>;
  evidence?: Array<number>;
}

export interface WatchLimits {
  maxEntities: number;
  maxSamples: number;
  maxBytes: number;
  maxOutputs: number;
  idleTTL: string;
}

export interface WatchMetadata {
  id: string;
  name?: string;
}

export interface WatchObservation {
  entity?: string;
  deadline?: string | null;
  sequence: number;
  inputId: string;
  acceptedAt: string;
  observedAt?: string | null;
  fields?: Record<string, unknown>;
  health: string;
  detail?: string;
}

export interface WatchPolicy {
  trigger: string;
  consecutive: number;
  recoverAfter: number;
  onUnknown: string;
  interval?: string;
  maxGap?: string;
}

export interface WatchSecretRef {
  env: string;
}

export interface WatchSource {
  observedAtField?: string;
  type: string;
  url?: string;
  urlRef?: WatchSecretRef | null;
  every?: string;
  timeout?: string;
  headers?: Record<string, WatchSecretRef>;
  fields?: Record<string, string>;
  jq?: string;
  argv?: Array<string>;
  directory?: string;
  env?: Record<string, WatchSecretRef>;
}

export interface WatchSpec {
  source: WatchSource;
  condition: WatchCondition;
  policy: WatchPolicy;
  groupBy?: Array<string>;
  match?: Record<string, unknown>;
  message?: string;
  destinations: Array<WatchTarget>;
  limits: WatchLimits;
}

export interface WatchTarget {
  ref: string;
  events: Array<string>;
}

export interface WatchrunApplyRequest {
  manifest: string;
  dryRun: boolean;
  expected?: Record<string, string>;
}

export interface WatchrunApplyResult {
  changes: Array<WatchrunChange>;
  dryRun: boolean;
}

export interface WatchrunChange {
  permissions: Array<string>;
  id: string;
  revision: string;
  previous?: string;
  state: string;
}

export interface WatchrunCredentialHealth {
  environment: string;
  present: boolean;
}

export interface WatchrunDoctor {
  healthy: boolean;
  store: StoreHealth;
  usage: StoreUsage;
  limits: WatchrunLimits;
  running: boolean;
  closing: boolean;
  acquisitions: number;
  acquisitionLimit: number;
  deliveryLimit: number;
  lastError?: string;
  sources: Array<WatchrunSourceHealth>;
  credentials: Array<WatchrunCredentialHealth>;
  deliveries: Record<string, number>;
}

export interface WatchrunLimits {
  maxWatches: number;
  maxPending: number;
  maxBytes: number;
  retention: number;
}

export interface WatchrunSourceHealth {
  id: string;
  status: string;
  lastInputAt: string;
  nextAt: string;
  lastError?: string;
  unhealthyEntities: number;
  openIncidents: number;
}

