// Generated by go run ./cmd/console-contract. Do not edit.

export interface ConditionSample {
  at: string;
  value: number;
  sequence: number;
}

export interface ConditionState {
  baselineSequence?: number;
  incidentEvent?: string;
  healthEvent?: string;
  freshSequence?: number;
  missingAt?: string;
  entity: string;
  open: boolean;
  matches: number;
  recoveries: number;
  lastAt: string;
  lastFired: string;
  lastSequence: number;
  sourceUnhealthy: boolean;
  samples?: Array<ConditionSample>;
  overflowUntil?: string;
  clockWindowUntil?: string;
  evidence?: Array<number>;
  baseline?: unknown;
  seen?: Record<string, string>;
}

export interface ControlBackupArtifact {
  id: string;
  bytes: number;
  expiresAt: string;
  verified: boolean;
}

export interface ControlBrowserSession {
  csrf: string;
  expiresAt: string;
}

export interface ControlCompileResult {
  valid: boolean;
  bundle: PlanBundle;
  descriptions: Array<PlanDescription>;
  diagnostics: Array<ControlDiagnostic>;
  credentials: Array<WatchrunCredentialHealth>;
}

export interface ControlConversion {
  report: MigrateReport;
  files: Array<ControlConvertedFile>;
  archive: string;
}

export interface ControlConvertedFile {
  name: string;
  content: string;
}

export interface ControlDiagnostic {
  code: string;
  severity: string;
  path: string;
  message: string;
  line?: number;
}

export interface ControlFirstWatchPreview {
  manifest: string;
  descriptions: Array<PlanDescription>;
  review: WatchrunApplyResult;
}

export interface ControlInfo {
  version: string;
  apiVersion: string;
  schema: number;
  os: string;
  arch: string;
  console: boolean;
  origin: string;
  listen: string;
  stateDir: string;
  limits: WatchrunLimits;
  time: string;
}

export interface ControlVerification {
  status: string;
  message: string;
}

export interface MigrateBinding {
  notifier: string;
  environment: string;
  from: string;
}

export interface MigrateIssue {
  code: string;
  message: string;
}

export interface MigrateReport {
  converted: number;
  unsupported: number;
  reviewRequired: boolean;
  state: string;
  warnings: Array<MigrateIssue>;
  bindings: Array<MigrateBinding>;
  rules: Array<MigrateRuleReport>;
}

export interface MigrateRuleReport {
  name: string;
  id: string;
  status: string;
  file?: string;
  issues: Array<MigrateIssue>;
  warnings: Array<MigrateIssue>;
}

export interface PlanBundle {
  watches: Array<PlanCompiled>;
  destinations: Array<PlanCompiledDestination>;
}

export interface PlanCompiled {
  definition: WatchDefinition;
  revision: string;
  fingerprint: string;
  permissions: Array<string>;
}

export interface PlanCompiledDestination {
  definition: WatchDestination;
  revision: string;
}

export interface PlanDescription {
  id: string;
  source: string;
  condition: string;
  policy: string;
}

export interface ReplayCheckpoint {
  prior: ConditionState;
  input: WatchObservation;
  sourceRecovered?: boolean;
}

export interface ReplayEvaluation {
  known: boolean;
  matched: boolean;
  reason: string;
  matches: number;
  recoveries: number;
  open: boolean;
  sourceUnhealthy: boolean;
  windows: Array<ReplayWindowSummary>;
}

export interface ReplayEvidence {
  evaluation?: ReplayEvaluation | null;
  definition: WatchDefinition;
  event: WatchEvent;
  checkpoint?: ReplayCheckpoint | null;
  replayStatus: string;
}

export interface ReplayReport {
  watchId: string;
  revision: string;
  observations: number;
  events: Array<WatchEvent>;
  states: Record<string, ConditionState>;
}

export interface ReplayWindowSummary {
  function: string;
  fromExclusive: string;
  throughInclusive: string;
  samples: number;
  value: number | null;
  available: boolean;
}

export interface StoreAttempt {
  attempt: number;
  at: string;
  outcome: string;
  detail: string;
}

export interface StoreConsoleDelivery {
  id: number;
  eventId: string;
  watchId: string;
  destinationId: string;
  destinationRevision: string;
  status: string;
  attempts: number;
  nextAt: string;
  createdAt: string;
  lastError: string;
}

export interface StoreConsoleDestination {
  definition: WatchDestination;
  revision: string;
  watches: number;
}

export interface StoreConsoleWatch {
  id: string;
  name: string;
  revision: string;
  status: string;
  source: string;
  trigger: string;
  operator: string;
  generation: number;
  nextAt: string;
  lastInputAt: string;
  lastError: string;
  entities: number;
  open: number;
  unhealthy: number;
  failed: number;
  pending: number;
  missing: Array<string>;
}

export interface StoreDeliveryInspection {
  intent: StoreIntent;
  attempts: Array<StoreAttempt>;
  before: number;
}

export interface StoreDeliveryPage {
  deliveries: Array<StoreConsoleDelivery>;
  total: number;
  counts: Record<string, number>;
  cursor: string;
  more: boolean;
  at: string;
}

export interface StoreDeliverySummary {
  id: number;
  eventId: string;
  destinationId: string;
  destinationRevision: string;
  status: string;
  attempts: number;
  nextAt: string;
  lastError?: string;
}

export interface StoreDestinationPage {
  destinations: Array<StoreConsoleDestination>;
  cursor: string;
  more: boolean;
}

export interface StoreEntitySummary {
  key: string;
  open: boolean;
  sourceUnhealthy: boolean;
  matches: number;
  recoveries: number;
  lastSequence: number;
  samples: number;
}

export interface StoreEventPage {
  events: Array<WatchEvent>;
  cursor: string;
  more: boolean;
}

export interface StoreEventSummary {
  id: string;
  sequence: number;
  watchId: string;
  revision: string;
  type: string;
  at: string;
  message: string;
  entity: string;
}

export interface StoreEventSummaryPage {
  events: Array<StoreEventSummary>;
  total: number;
  cursor: string;
  followCursor: string;
  more: boolean;
  at: string;
}

export interface StoreHealth {
  sqlite: string;
  schema: number;
  journal: string;
  synchronous: number;
  integrity: string;
  databaseBytes: number;
  walBytes: number;
}

export interface StoreIntent {
  id: number;
  eventId: string;
  watchId: string;
  destinationId: string;
  destinationRevision: string;
  payload: string;
  status: string;
  attempts: number;
  nextAt: string;
  cycleStartedAt: string;
  createdAt: string;
}

export interface StoreObservationPage {
  observations: Array<WatchObservation>;
  after: number;
  more: boolean;
}

export interface StoreUsage {
  watches: number;
  pending: number;
  liveBytes: number;
  observations: number;
  events: number;
  entities: number;
  timers: number;
}

export interface StoreWatchPage {
  watches: Array<StoreConsoleWatch>;
  total: number;
  all: number;
  attention: number;
  paused: number;
  cursor: string;
  more: boolean;
  at: string;
}

export interface StoreWatchRecord {
  plan: PlanCompiled;
  generation: number;
  status: string;
  nextAt: string;
  cursor?: string;
  lastInputAt?: string;
  lastError?: string;
}

export interface StoreWatchSummary {
  watch: StoreWatchRecord;
  entities: Array<StoreEntitySummary>;
  entitiesAfter: string;
  entitiesMore: boolean;
  deliveries: Array<StoreDeliverySummary>;
  deliveriesBefore: number;
  deliveriesMore: boolean;
}

export interface WatchCondition {
  field?: string;
  operator?: string;
  value: unknown;
  numeric?: string;
  missingFor?: string;
  dedupFor?: string;
}

export interface WatchDefinition {
  apiVersion: string;
  kind: string;
  metadata: WatchMetadata;
  spec: WatchSpec;
}

export interface WatchDestination {
  apiVersion: string;
  kind: string;
  metadata: WatchMetadata;
  spec: WatchDestinationSpec;
}

export interface WatchDestinationSpec {
  type: string;
  urlRef?: WatchSecretRef | null;
  headers?: Record<string, WatchSecretRef>;
  maxAttempts: number;
  maxAge: string;
  initialBackoff: string;
}

export interface WatchEvent {
  id: string;
  sequence: number;
  watchId: string;
  revision: string;
  entity: string;
  type: string;
  at: string;
  message: string;
  fields?: Record<string, unknown>;
  evidence?: Array<number>;
}

export interface WatchLimits {
  maxEntities: number;
  maxSamples: number;
  maxBytes: number;
  maxOutputs: number;
  idleTTL: string;
}

export interface WatchMetadata {
  id: string;
  name?: string;
}

export interface WatchObservation {
  entity?: string;
  deadline?: string | null;
  sequence: number;
  inputId: string;
  acceptedAt: string;
  observedAt?: string | null;
  fields?: Record<string, unknown>;
  health: string;
  detail?: string;
}

export interface WatchPolicy {
  trigger: string;
  consecutive: number;
  recoverAfter: number;
  onUnknown: string;
  interval?: string;
  maxGap?: string;
}

export interface WatchSecretRef {
  env: string;
}

export interface WatchSource {
  observedAtField?: string;
  type: string;
  url?: string;
  urlRef?: WatchSecretRef | null;
  every?: string;
  timeout?: string;
  headers?: Record<string, WatchSecretRef>;
  fields?: Record<string, string>;
  jq?: string;
  argv?: Array<string>;
  directory?: string;
  env?: Record<string, WatchSecretRef>;
}

export interface WatchSpec {
  source: WatchSource;
  condition: WatchCondition;
  policy: WatchPolicy;
  groupBy?: Array<string>;
  match?: Record<string, unknown>;
  message?: string;
  destinations: Array<WatchTarget>;
  limits: WatchLimits;
}

export interface WatchTarget {
  ref: string;
  events: Array<string>;
}

export interface WatchrunApplyPreconditions {
  instance: string;
  manifestHash: string;
  watches: Record<string, WatchrunWatchPrecondition>;
  destinations: Record<string, string>;
}

export interface WatchrunApplyRequest {
  review?: WatchrunApplyPreconditions | null;
  manifest: string;
  dryRun: boolean;
  expected?: Record<string, string>;
}

export interface WatchrunApplyResult {
  destinationChanges: Array<WatchrunChange>;
  review: WatchrunApplyPreconditions | null;
  credentials: Array<WatchrunCredentialHealth>;
  changes: Array<WatchrunChange>;
  dryRun: boolean;
}

export interface WatchrunChange {
  kind: string;
  before?: string;
  after?: string;
  permissions: Array<string>;
  id: string;
  revision: string;
  previous?: string;
  state: string;
}

export interface WatchrunCredentialHealth {
  environment: string;
  present: boolean;
}

export interface WatchrunDoctor {
  healthy: boolean;
  store: StoreHealth;
  usage: StoreUsage;
  limits: WatchrunLimits;
  running: boolean;
  closing: boolean;
  acquisitions: number;
  acquisitionLimit: number;
  deliveryLimit: number;
  lastError?: string;
  sources: Array<WatchrunSourceHealth>;
  credentials: Array<WatchrunCredentialHealth>;
  deliveries: Record<string, number>;
}

export interface WatchrunLimits {
  maxWatches: number;
  maxPending: number;
  maxBytes: number;
  retention: number;
}

export interface WatchrunSourceHealth {
  id: string;
  status: string;
  lastInputAt: string;
  nextAt: string;
  lastError?: string;
  unhealthyEntities: number;
  openIncidents: number;
  acquisition: string;
  overdueSeconds: number;
}

export interface WatchrunStatus {
  instance: string;
  running: boolean;
  closing: boolean;
  acquisitions: number;
  lastError: string;
  at: string;
}

export interface WatchrunWatchPrecondition {
  revision: string;
  generation: number;
  status: string;
}

